# Generated by Django 2.2.2 on 2019-06-28 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
