# Generated by Django 2.2.2 on 2019-07-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('password', models.CharField(max_length=500)),
                ('Employee_Id', models.CharField(max_length=500, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Login',
            },
        ),
    ]
