# Generated by Django 2.2.2 on 2019-07-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='Employee_Id',
            new_name='emp_Id',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='password',
            new_name='emp_password',
        ),
    ]
