# Generated by Django 2.2.2 on 2019-07-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20190701_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='emp_Id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='emp_password',
            new_name='emp_pas',
        ),
    ]
