# Generated by Django 2.2.2 on 2019-07-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quer1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name2', models.CharField(max_length=1000)),
                ('id2', models.CharField(max_length=1000)),
                ('bond2', models.CharField(max_length=1000)),
                ('use2', models.BooleanField(blank=True)),
                ('type2', models.CharField(max_length=1000)),
            ],
        ),
    ]
