# Generated by Django 2.2.2 on 2019-07-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='request_id',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
