# Generated by Django 2.2.2 on 2019-07-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrequest', '0002_auto_20190709_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='emp_id',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
