# Generated by Django 2.2.2 on 2019-07-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0005_auto_20190701_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRequest',
            fields=[
                ('item_name', models.CharField(max_length=1000)),
                ('date', models.DateTimeField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=500, primary_key=True, serialize=False)),
                ('emp_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='signup.Employee')),
            ],
            options={
                'db_table': 'NewReuest',
            },
        ),
    ]
