# Generated by Django 2.2.2 on 2019-07-03 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newrequest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrequest',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='newrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newrequest',
            name='emp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.Employee'),
        ),
        migrations.AlterField(
            model_name='newrequest',
            name='request_id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
