# Generated by Django 2.2.2 on 2019-07-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newrequest', '0002_auto_20190703_1350'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newrequest',
            table='NewRequest',
        ),
    ]
