# Generated by Django 2.2.2 on 2019-07-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrequest', '0004_auto_20190708_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrequest',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
