# Generated by Django 2.2.2 on 2019-07-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newrequest', '0005_auto_20190716_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newrequest',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
