# Generated by Django 2.2.2 on 2019-07-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useradmin',
            fields=[
                ('emailaddress', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('Employee_Id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'useradmin',
            },
        ),
    ]
