# Generated by Django 2.2.2 on 2019-07-04 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0004_auto_20190704_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='item',
        ),
    ]
