# Generated by Django 2.2.2 on 2019-07-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0005_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Replacement_Completed',
        ),
        migrations.AddField(
            model_name='items',
            name='Location',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='items',
            name='Name',
            field=models.CharField(max_length=1000),
        ),
    ]
