# Generated by Django 2.2.2 on 2019-07-05 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0006_auto_20190704_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='Unique_Id',
            new_name='id',
        ),
    ]
