# Generated by Django 2.2.2 on 2019-07-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0007_auto_20190705_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Date_Of_Upgrade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='In_use',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Loaned',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Model',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Photograph',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='items',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Replacement_Required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='To_be_Discarded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Vendor_No',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
