# Generated by Django 2.2.2 on 2019-07-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0008_auto_20190705_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Asset_Value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
