# Generated by Django 2.2.2 on 2019-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0010_auto_20190705_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Bond_Id',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='items',
            name='Description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='items',
            name='Type',
            field=models.CharField(max_length=1000),
        ),
    ]
