# Generated by Django 2.2.2 on 2019-07-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0011_auto_20190705_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Asset_Value',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
