# Generated by Django 2.2.2 on 2019-07-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0014_auto_20190708_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.CharField(max_length=1000)),
                ('Condition', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'db_table': 'returnmodel',
            },
        ),
    ]
