# Generated by Django 2.2.2 on 2019-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0018_auto_20190715_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='items',
            name='Type',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
