# Generated by Django 2.2.2 on 2019-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0019_auto_20190715_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Bond_Id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
