# Generated by Django 2.2.2 on 2019-07-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0020_auto_20190715_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='Name',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
